module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./napolean.jpg'),
	"menu": require('./hamburger.png'),
	"info": require('./info.png'),

	"coalition": require('./coalition.jpg'),
	"imperial": require('./imperial.jpg'),

	"refreshButton": require('./ic_action_refresh.png'),
	"prevButton":	require('./ic_action_previous_item.png'),
	"nextButton": require('./ic_action_next_item.png'),
	"radio-on": require('./radio-on.png'),
	"radio-off": require('./radio-off.png'),

	"arrowRight": require('./arrow-right.png'),
	"arrowDown": require('./arrow-down.png'),
	"add": require('./addico.png'),
	"equal": require('./equalico.png'),

	"NE": require('./no-effect.png'),
	"1": require('./1.png'),
	"2": require('./2.png'),
	"3": require('./3.png'),
	"4": require('./4.png'),
	"5": require('./5.png'),

	"pass": require('./pass.png'),
	"fail": require('./fail.jpg'),
	"Stand": require('./stand.png'),
	"Square": require('./square.png'),
	"Carre": require('./square.png'),
	"Disorder": require('./disorder.png'),
	"Route": require('./route.png'),

	"attackerLoss": require('./attacker.png'),
	"defenderLoss": require('./defender.png'),
	"wounded": require('./ambulance.png'),
	"mortal": require('./tombstone.png'),
	"capture": require('./capture.jpg'),

	"French": require('./french_flag.jpg'),
	"Polish": require('./polish_flag.png'),
	"Russian": require('./russian_flag.png'),
	"Austrian": require('./austrian_flag.png'),
	"Prussian": require('./prussian_flag.png'),

	"halle": require("./halle.jpg"),
	"raszyn": require("./raszyn.jpg"),
	"leipzig": require("./leipzig.jpg"),
	"friedland": require("./friedland.jpg"),
	"aspern_essling": require("./aspern_essling.jpg"),
	"neumarkt": require("./neumarkt.jpg"),
	"schoengrabern": require("./schoengrabern.png"),
	"vauchamps": require("./vauchamps.jpg"),
	"auerstaedt": require("./auerstaedt.jpg"),
	"eylau": require("./eylau.jpg"),
	"talavera": require("./talavera.jpg"),
	"albuera": require("./albuera.jpg"),
	"ligny": require("./ligny.jpg"),
	"quatrebras": require("./quatrebras.jpg"),
	"montstjean": require("./montstjean.jpg"),
	"wavre": require("./wavre.jpg"),
	"corunna": require("./corunna.jpg"),
	"luetzen": require("./luetzen.jpg"),
	"orthez": require("./orthez.jpg"),
	"moscowa": require("./moscowa.jpg")
};
