module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./napolean.jpg'),
	"menu": require('./hamburger.png'),
	"info": require('./info.png'),

	"coalition": require('./coalition.jpg'),
	"imperial": require('./imperial.jpg'),

	"refreshButton": require('./ic_action_refresh.png'),
	"prevButton":	require('./ic_action_previous_item.png'),
	"nextButton": require('./ic_action_next_item.png'),

	"arrowRight": require('./arrow-right.png'),
	"arrowDown": require('./arrow-down.png'),

	"NE": require('./no-effect.jpg'),
	"1": require('./1.png'),
	"2": require('./2.png'),
	"3": require('./3.png'),
	"4": require('./4.png'),
	"5": require('./5.png'),

	"pass": require('./pass.png'),
	"fail": require('./fail.jpg'),

	"attackerLoss": require('./attacker.png'),
	"defenderLoss": require('./defender.png'),
	"wounded": require('./ambulance.png'),
	"mortal": require('./tombstone.png'),
	"capture": require('./capture.jpg'),

	"halle": require("./halle.jpg"),
	"halle-sm": require("./halle-sm.jpg"),
	"raszyn": require("./raszyn.jpg"),
	"raszyn-sm": require("./raszyn-sm.jpg"),
	"leipzig": require("./leipzig.jpg"),
	"leipzig-sm": require("./leipzig-sm.jpg"),
	"friedland": require("./friedland.jpg"),
	"friedland-sm": require("./friedland-sm.jpg"),
	"aspern_essling": require("./aspern_essling.jpg"),
	"aspern_essling-sm": require("./aspern_essling-sm.jpg"),
	"neumarkt": require("./neumarkt.jpg"),
	"neumarkt-sm": require("./neumarkt-sm.jpg"),
	"schoengrabern": require("./schoengrabern.png"),
	"schoengrabern-sm": require("./schoengrabern-sm.png"),
	"vauchamps": require("./vauchamps.jpg"),
	"vauchamps-sm": require("./vauchamps-sm.jpg"),
	"auerstaedt": require("./auerstaedt.jpg"),
	"auerstaedt-sm": require("./auerstaedt-sm.jpg"),
	"eylau": require("./eylau.jpg"),
	"eylau-sm": require("./eylau-sm.jpg"),
	"talavera": require("./talavera.jpg"),
	"talavera-sm": require("./talavera-sm.jpg"),
	"albuera": require("./albuera.jpg"),
	"albuera-sm": require("./albuera-sm.jpg"),
	"ligny": require("./ligny.jpg"),
	"ligny-sm": require("./ligny-sm.jpg"),
	"quatrebras": require("./quatrebras.jpg"),
	"quatrebras-sm": require("./quatrebras-sm.jpg"),
	"montstjean": require("./montstjean.jpg"),
	"montstjean-sm": require("./montstjean-sm.jpg"),
	"wavre": require("./wavre.jpg"),
	"wavre-sm": require("./wavre-sm.jpg"),
	"corunna": require("./corunna.jpg"),
	"corunna-sm": require("./corunna-sm.jpg"),
	"luetzen": require("./luetzen.jpg"),
	"luetzen-sm": require("./luetzen-sm.jpg"),
	"orthez": require("./orthez.jpg"),
	"orthez-sm": require("./orthez-sm.jpg"),
	"moscowa": require("./moscowa.jpg"),
	"moscowa-sm": require("./moscowa-sm.jpg")
};
