import { Icons } from 'react-native-nub';

module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./napolean.jpg'),
	"menu": Icons['menu-dark'],
	"info": Icons['info-dark'],
	"refresh": Icons['refresh-dark'],
	"back": Icons['chevron-left-dark'],
	"config": Icons['gear-dark'],

	"draw": require('./draw-from-cup.png'),
	"drawcup": require('./drawcup.png'),
	"resetcup": require('./reset-draw-cup.png'),
    "regroup": require('./regroup.png'),
    "reinforcements": require('./reinforcements.png'),
    "leader": require('./leader.png'),
    "artillery": require('./artillery.png'),
	
	"add": require('./add.png'),
	"equal": require('./equal.png'),

	"NE": require('./no-effect.png'),
	"1": require('./1.png'),
	"2": require('./2.png'),
	"3": require('./3.png'),
	"4": require('./4.png'),
	"5": require('./5.png'),
	"6": require('./6.png'),
	"7": require('./7.png'),
	"8": require('./8.png'),
	"9": require('./9.png'),
	"10": require('./10.png'),

	"pass": require('./pass.png'),
	"fail": require('./fail.png'),
	"Stand": require('./stand.png'),
	"Square": require('./square.png'),
	"Carre": require('./square.png'),
	"Disorder": require('./disorder.png'),
	"Rout": require('./rout.png'),
	"ride": require('./cavalry-ride.png'),
	"recall": require('./cavalry-recall.png'),

	"wounded": require('./ambulance.png'),
	"mortal": require('./tombstone.png'),
	"capture": require('./capture.jpg'),
	"arm": require('./arm.png'),
	"leg": require('./leg.png'),
	"stun": require('./stun.png'),
	"flesh": require('./flesh.png'),

	"French": require('./french_flag.jpg'),
	"Polish": require('./polish_flag.png'),
	"Saxons": require('./saxony_flag.png'),
	"Dutch": require('./dutch_flag.png'),
	"Russian": require('./russian_flag.png'),
	"Austrian": require('./austrian_flag.png'),
	"Hungarian": require('./hungary_flag.png'),	
	"Prussian": require('./prussian_flag.png'),
	"British": require('./british_flag_1.jpg'),
	"Spanish": require('./spanish flag cross.jpg'),
	"Portuguese": require('./portuguese_flag.jpg'),
	"AustrianRussian": require('./austrian_russian.png'),
	"PrussianAustrianRussian": require('./prussian_austrian_russian.png'),
	"PrussianRussian": require('./prussian_russian.png'),
	"AngloPrussian": require('./anglo_prussian.png'),
	"AngloSpanish": require('./anglo_spanish.png'),
	"imperial": require('./imperial.jpg'),
	"coalition": require('./coalition.jpg'),	

	"BritishKGL": require('./britishkgl_ml.png'),	
	"Nassau": require('./nassau_ml.png'),	
	"Dutch-Belgian": require('./dutch-belgian_ml.png'),	
	"Brunswick": require('./brunswick_ml.png'),	
	"Hanovarian": require('./hanovarian_ml.png'),	

	"Clash of Arms": require('./coa-logo.png'),
	//"Marshal Enterprises": require('./me-logo.png'),
	"ATO": require('./ato-logo.png'),

	"halle": require("./halle.jpg"),
	"raszyn": require("./raszyn.jpg"),
	"leipzig": require("./leipzig.jpg"),
	"friedland": require("./friedland.jpg"),
	"aspern_essling": require("./aspern_essling.jpg"),
	"neumarkt": require("./neumarkt.jpg"),
	"schoengrabern": require("./schoengrabern.png"),
	"austerlitz": require("./austerlitz.png"),
	"prusse": require("./prusse.png"),	
	"wagram": require("./wagram.png"),	
	"bautzen": require("./bautzen.png"),	
	"vauchamps": require("./vauchamps.jpg"),
	"auerstaedt": require("./auerstaedt.jpg"),
	"eylau": require("./eylau.jpg"),
	"talavera": require("./talavera.jpg"),
	"albuera": require("./albuera.jpg"),
	"ligny": require("./ligny.jpg"),
	"quatrebras": require("./quatrebras.png"),
	"ligny-quatrebras": require("./ligny-quatrebras.png"),
	"montstjean": require("./montstjean.jpg"),
	"wavre": require("./wavre.jpg"),
	"corunna": require("./corunna.jpg"),
	"luetzen": require("./luetzen.jpg"),
	"orthez": require("./orthez.jpg"),
	"moscowa": require("./moscowa.jpg")
};
