import { Icons } from 'react-native-nub';

module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./napolean.jpg'),
	"menu": Icons['menu-dark'],
	"info": Icons['info-dark'],
	"refresh": Icons['refresh-dark'],
	"back": Icons['chevron-left-dark'],
	"config": Icons['gear-dark'],

	"draw": require('./draw-from-cup.png'),
	"drawcup": require('./drawcup.png'),
	"resetcup": require('./reset-draw-cup.png'),
    "regroup": require('./regroup.png'),
    "reinforcements": require('./reinforcements.png'),
    "leader": require('./leader.png'),
    "artillery": require('./artillery.png'),
	
	"add": require('./add.png'),
	"equal": require('./equal.png'),

	"NE": require('./no-effect.png'),
	"1": require('./1.png'),
	"2": require('./2.png'),
	"3": require('./3.png'),
	"4": require('./4.png'),
	"5": require('./5.png'),
	"6": require('./6.png'),
	"7": require('./7.png'),
	"8": require('./8.png'),
	"9": require('./9.png'),
	"10": require('./10.png'),

	"pass": require('./pass.png'),
	"fail": require('./fail.png'),
	"Stand": require('./stand.png'),
	"Square": require('./square.png'),
	"Carre": require('./square.png'),
	"Disorder": require('./disorder.png'),
	"Rout": require('./rout.png'),
	"ride": require('./cavalry-ride.png'),
	"recall": require('./cavalry-recall.png'),

	"wounded": require('./ambulance.png'),
	"mortal": require('./tombstone.png'),
	"capture": require('./capture.jpg'),
	"arm": require('./arm.png'),
	"leg": require('./leg.png'),
	"stun": require('./stun.png'),
	"flesh": require('./flesh.png'),

	"French": require('./french_flag.jpg'),
	"Polish": require('./polish_flag.png'),
	"Saxons": require('./saxony_flag.png'),
	"Dutch": require('./dutch_flag.png'),
	"Russian": require('./russian_flag.png'),
	"Austrian": require('./austrian_flag.png'),
	"Hungarian": require('./hungary_flag.png'),	
	"Prussian": require('./prussian_flag.png'),
	"British": require('./british_flag_1.jpg'),
	"Spanish": require('./spanish flag cross.jpg'),
	"Portuguese": require('./portuguese_flag.jpg'),
	"AustrianRussian": require('./austrian_russian.png'),
	"PrussianAustrianRussian": require('./prussian_austrian_russian.png'),
	"PrussianRussian": require('./prussian_russian.png'),
	"AngloPrussian": require('./anglo_prussian.png'),
	"AngloSpanish": require('./anglo_spanish.png'),
	"imperial": require('./imperial.jpg'),
	"coalition": require('./coalition.jpg'),	

	"BritishKGL": require('./britishkgl_ml.png'),	
	"Nassau": require('./nassau_ml.png'),	
	"Dutch-Belgian": require('./dutch-belgian_ml.png'),	
	"Brunswick": require('./brunswick_ml.png'),	
	"Hanovarian": require('./hanovarian_ml.png'),	
	
	"terrain_clear": require('./terrain_clear.png'),
	"terrain_hamlet": require('./terrain_hamlet.png'),
	"terrain_village": require('./terrain_village.png'),
	"terrain_town": require('./terrain_town.png'),
	"terrain_earthworks": require('./terrain_earthworks.png'),
	"terrain_carpponds": require('./terrain_carpponds.png'),
	"terrain_entrenchments": require('./terrain_entrenchments.png'),
	"terrain_swamp": require('./terrain_swamp.png'),
	"terrain_woods": require('./terrain_woods.png'),
	"terrain_garden": require('./terrain_garden.png'),
	"terrain_slope": require('./terrain_slope.png'),
	"terrain_road": require('./terrain_road.png'),
	"terrain_bridge": require('./terrain_bridge.png'),
	"terrain_streams": require('./terrain_streams.png'),
	"terrain_ford": require('./terrain_ford.png'),
	"terrain_spree": require('./terrain_spree.png'),
	"terrain_woodspathway": require('./terrain_woodspathway.png'),
	"terrain_schiessscharte": require('./terrain_schiessscharte.png'),
	"terrain_wall": require('./terrain_wall.png'),

	"terrain_redoubt": require('./terrain_redoubt.png'),
	
	"terrain_woods2": require('./terrain_woods2.png'),
	"terrain_forest": require('./terrain_forest.png'),
	"terrain_orchard": require('./terrain_orchard.png'),
	"terrain_marsh": require('./terrain_marsh.png'),
	"terrain_road2": require('./terrain_road2.png'),
	"terrain_road_marsh": require('./terrain_road_marsh.png'),
	"terrain_bridge_river": require('./terrain_bridge_river.png'),
	"terrain_bridge_stream": require('./terrain_bridge_stream.png'),
	"terrain_landdamm": require('./terrain_landdamm.png'),
	"terrain_hamlet2": require('./terrain_hamlet2.png'),
	"terrain_village2": require('./terrain_village2.png'),

	
	"terrain_woods3": require('./terrain_woods3.png'),
	"terrain_forest2": require('./terrain_forest2.png'),
	"terrain_orchard2": require('./terrain_orchard2.png'),
	"terrain_swamp2": require('./terrain_swamp2.png'),
	"terrain_marsh": require('./terrain_marsh.png'),
	"terrain_road2": require('./terrain_road2.png'),
	"terrain_road_marsh2": require('./terrain_road_marsh2.png'),
	"terrain_bridge_river2": require('./terrain_bridge_river2.png'),
	"terrain_bridge_stream2": require('./terrain_bridge_stream2.png'),
	"terrain_landdamm": require('./terrain_landdamm.png'),	
	"terrain_lane": require('./terrain_lane.png'),
	"terrain_village3": require('./terrain_village3.png'),
	"terrain_garden2": require('./terrain_garden2.png'),
	"terrain_slope2": require('./terrain_slope2.png'),

	"Clash of Arms": require('./coa-logo.png'),
	//"Marshal Enterprises": require('./me-logo.png'),
	"ATO": require('./ato-logo.png'),

	"halle": require("./halle.jpg"),
	"raszyn": require("./raszyn.jpg"),
	"leipzig": require("./leipzig.jpg"),
	"friedland": require("./friedland.jpg"),
	"danzig": require("./danzig.jpg"),
	"aspern_essling": require("./aspern_essling.jpg"),
	"neumarkt": require("./neumarkt.jpg"),
	"schoengrabern": require("./schoengrabern.png"),
	"austerlitz": require("./austerlitz.png"),
	"prusse": require("./prusse.png"),	
	"wagram": require("./wagram.png"),	
	"bautzen": require("./bautzen.png"),	
	"hagelberg": require("./hagelberg.png"),	
	"vauchamps": require("./vauchamps.jpg"),
	"auerstaedt": require("./auerstaedt.jpg"),
	"eylau": require("./eylau.jpg"),
	"talavera": require("./talavera.jpg"),
	"albuera": require("./albuera.jpg"),
	"ligny": require("./ligny.jpg"),
	"quatrebras": require("./quatrebras.png"),
	"ligny-quatrebras": require("./ligny-quatrebras.png"),
	"montstjean": require("./montstjean.jpg"),
	"wavre": require("./wavre.jpg"),
	"corunna": require("./corunna.jpg"),
	"luetzen": require("./luetzen.jpg"),
	"orthez": require("./orthez.jpg"),
	"moscowa": require("./moscowa.jpg"),
	"wartenburg": require("./wartenburg.png")
};
