import { Icons } from 'react-native-nub';

module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./napolean.jpg'),
	"menu": Icons['menu-dark'],
	"info": Icons['info-dark'],
	"refresh": Icons['refresh-dark'],
	"back": Icons['chevron-left-dark'],
	"config": Icons['gear-dark'],

	"draw": require('./draw-from-cup.png'),
	"drawcup": require('./drawcup.png'),
	"resetcup": require('./reset-draw-cup.png'),
    "regroup": require('./regroup.png'),
    "reinforcements": require('./reinforcements.png'),
    "leader": require('./leader.png'),
    "artillery": require('./artillery.png'),
	
	"add": require('./addico.png'),
	"equal": require('./equalico.png'),

	"NE": require('./no-effect.png'),
	"1": require('./1.png'),
	"2": require('./2.png'),
	"3": require('./3.png'),
	"4": require('./4.png'),
	"5": require('./5.png'),

	"pass": require('./pass.png'),
	"fail": require('./fail.png'),
	"Stand": require('./stand.png'),
	"Square": require('./square.png'),
	"Carre": require('./square.png'),
	"Disorder": require('./disorder.png'),
	"Rout": require('./rout.png'),

	"wounded": require('./ambulance.png'),
	"mortal": require('./tombstone.png'),
	"capture": require('./capture.jpg'),
	"arm": require('./arm.png'),
	"leg": require('./leg.png'),

	"French": require('./french_flag.jpg'),
	"Polish": require('./polish_flag.png'),
	"Saxons": require('./saxony_flag.png'),
	"Dutch": require('./dutch_flag.png'),
	"Russian": require('./russian_flag.png'),
	"Austrian": require('./austrian_flag.png'),
	"Hungarian": require('./hungary_flag.png'),	
	"Prussian": require('./prussian_flag.png'),
	"British": require('./british_flag_1.jpg'),
	"AustrianRussian": require('./austrian_russian.png'),
	"PrussianAustrianRussian": require('./prussian_austrian_russian.png'),
	"PrussianRussian": require('./prussian_russian.png'),
	"AngloPrussian": require('./anglo_prussian.png'),
	"AngloSpanish": require('./anglo_spanish.png'),
	"imperial": require('./imperial.jpg'),
	"coalition": require('./coalition.jpg'),	

	"halle": require("./halle.jpg"),
	"raszyn": require("./raszyn.jpg"),
	"leipzig": require("./leipzig.jpg"),
	"friedland": require("./friedland.jpg"),
	"aspern_essling": require("./aspern_essling.jpg"),
	"neumarkt": require("./neumarkt.jpg"),
	"schoengrabern": require("./schoengrabern.png"),
	"austerlitz": require("./austerlitz.png"),
	"vauchamps": require("./vauchamps.jpg"),
	"auerstaedt": require("./auerstaedt.jpg"),
	"eylau": require("./eylau.jpg"),
	"talavera": require("./talavera.jpg"),
	"albuera": require("./albuera.jpg"),
	"ligny": require("./ligny.jpg"),
	"quatrebras": require("./quatrebras.jpg"),
	"montstjean": require("./montstjean.jpg"),
	"wavre": require("./wavre.jpg"),
	"corunna": require("./corunna.jpg"),
	"luetzen": require("./luetzen.jpg"),
	"orthez": require("./orthez.jpg"),
	"moscowa": require("./moscowa.jpg")
};
