module.exports = {
	"logo": require('./resources/lb.jpg'),
	"splash": require('./resources/napolean.jpg'),
	"refreshButton": require('./resources/ic_action_refresh.png'),
	"prevButton":	require('./resources/ic_action_previous_item.png'),
	"nextButton": require('./resources/ic_action_next_item.png'),

	"attackerLoss": require('./resources/attacker.png'),
	"defenderLoss": require('./resources/defender.png'),
	"wounded": require('./resources/ambulance.png'),
	"mortal": require('./resources/tombstone.png'),
	
	"halle": require("./resources/halle.jpg"),
	"raszyn": require("./resources/raszyn.jpg"),
	"leipzig": require("./resources/leipzig.jpg"),
	"friedland": require("./resources/friedland.jpg"),
	"aspern_essling": require("./resources/aspern_essling.jpg"),
	"neumarkt": require("./resources/neumarkt.jpg"),
	"vauchamps": require("./resources/vauchamps.jpg"),
	"auerstaedt": require("./resources/auerstaedt.jpg"),
	"eylau": require("./resources/eylau.jpg"),
	"talavera": require("./resources/talavera.jpg"),
	"albuera": require("./resources/albuera.jpg"),
	"ligny": require("./resources/ligny.jpg"),
	"quatrebras": require("./resources/quatrebras.jpg"),
	"montstjean": require("./resources/montstjean.jpg"),
	"wavre": require("./resources/wavre.jpg"),
	"corunna": require("./resources/corunna.jpg"),
	"luetzen": require("./resources/luetzen.jpg"),
	"orthez": require("./resources/orthez.jpg"),
	"moscowa": require("./resources/moscowa.jpg")
};
