module.exports = {
	"logo": require('./resources/logo.png'),
	"splash": require('./resources/napolean.jpg'),
	"menu": require('./resources/hamburger.png'),
	"info": require('./resources/info.png'),

	"coalition": require('./resources/coalition.jpg'),
	"imperial": require('./resources/imperial.jpg'),

	"refreshButton": require('./resources/ic_action_refresh.png'),
	"prevButton":	require('./resources/ic_action_previous_item.png'),
	"nextButton": require('./resources/ic_action_next_item.png'),

	"arrowRight": require('./resources/arrow-right.png'),
	"arrowDown": require('./resources/arrow-down.png'),

	"NE": require('./resources/no-effect.jpg'),
	"1": require('./resources/1.png'),
	"2": require('./resources/2.png'),
	"3": require('./resources/3.png'),
	"4": require('./resources/4.png'),
	"5": require('./resources/5.png'),

	"pass": require('./resources/pass.png'),
	"fail": require('./resources/fail.jpg'),

	"attackerLoss": require('./resources/attacker.png'),
	"defenderLoss": require('./resources/defender.png'),
	"wounded": require('./resources/ambulance.png'),
	"mortal": require('./resources/tombstone.png'),
	"capture": require('./resources/capture.jpg'),

	"halle": require("./resources/halle.jpg"),
	"halle-sm": require("./resources/halle-sm.jpg"),
	"raszyn": require("./resources/raszyn.jpg"),
	"raszyn-sm": require("./resources/raszyn-sm.jpg"),
	"leipzig": require("./resources/leipzig.jpg"),
	"leipzig-sm": require("./resources/leipzig-sm.jpg"),
	"friedland": require("./resources/friedland.jpg"),
	"friedland-sm": require("./resources/friedland-sm.jpg"),
	"aspern_essling": require("./resources/aspern_essling.jpg"),
	"aspern_essling-sm": require("./resources/aspern_essling-sm.jpg"),
	"neumarkt": require("./resources/neumarkt.jpg"),
	"neumarkt-sm": require("./resources/neumarkt-sm.jpg"),
	"schoengrabern": require("./resources/schoengrabern.png"),
	"schoengrabern-sm": require("./resources/schoengrabern-sm.png"),
	"vauchamps": require("./resources/vauchamps.jpg"),
	"vauchamps-sm": require("./resources/vauchamps-sm.jpg"),
	"auerstaedt": require("./resources/auerstaedt.jpg"),
	"auerstaedt-sm": require("./resources/auerstaedt-sm.jpg"),
	"eylau": require("./resources/eylau.jpg"),
	"eylau-sm": require("./resources/eylau-sm.jpg"),
	"talavera": require("./resources/talavera.jpg"),
	"talavera-sm": require("./resources/talavera-sm.jpg"),
	"albuera": require("./resources/albuera.jpg"),
	"albuera-sm": require("./resources/albuera-sm.jpg"),
	"ligny": require("./resources/ligny.jpg"),
	"ligny-sm": require("./resources/ligny-sm.jpg"),
	"quatrebras": require("./resources/quatrebras.jpg"),
	"quatrebras-sm": require("./resources/quatrebras-sm.jpg"),
	"montstjean": require("./resources/montstjean.jpg"),
	"montstjean-sm": require("./resources/montstjean-sm.jpg"),
	"wavre": require("./resources/wavre.jpg"),
	"wavre-sm": require("./resources/wavre-sm.jpg"),
	"corunna": require("./resources/corunna.jpg"),
	"corunna-sm": require("./resources/corunna-sm.jpg"),
	"luetzen": require("./resources/luetzen.jpg"),
	"luetzen-sm": require("./resources/luetzen-sm.jpg"),
	"orthez": require("./resources/orthez.jpg"),
	"orthez-sm": require("./resources/orthez-sm.jpg"),
	"moscowa": require("./resources/moscowa.jpg"),
	"moscowa-sm": require("./resources/moscowa-sm.jpg")
};
