module.exports = {
	"halle": require("image!halle"),
	"raszyn": require("image!raszyn"),
	"leipzig": require("image!leipzig"),
	"friedland": require("image!friedland"),
	"aspern_essling": require("image!aspern_essling"),
	"neumarkt": require("image!neumarkt"),
	"vauchamps": require("image!vauchamps"),
	"auerstaedt": require("image!auerstaedt"),
	"eylau": require("image!eylau"),
	"talavera": require("image!talavera"),
	"albuera": require("image!albuera"),
	"ligny": require("image!ligny"),
	"quatrebras": require("image!quatrebras"),
	"montstjean": require("image!montstjean"),
	"wavre": require("image!wavre"),
	"corunna": require("image!corunna"),
	"luetzen": require("image!luetzen"),
	"orthez": require("image!orthez"),
	"moscowa": require("image!moscowa")
};
