module.exports = {
    TOAST: 'TOAST',
    SET_CURRENT: 'SET_CURRENT',
    SET_MODE: 'SET_RULESET',
    PREV_TURN: 'PREV_TURN',
    NEXT_TURN: 'NEXT_TURN',
    PREV_PHASE: 'PREV_PHASE',
    NEXT_PHASE: 'NEXT_PHASE',
    NEXT_PLAYER: 'NEXT_PLAYER',
    SET_VICTORY: 'SET_VICTORY'
};
