module.exports = {
    TOAST: 'TOAST',
    SET_CURRENT: 'SET_CURRENT',
    SET_RULESET: 'SET_RULESET',
    SET_MUCUP: 'SET_MUCUP',
    SET_MU: 'SET_MU',
    PREV_TURN: 'PREV_TURN',
    NEXT_TURN: 'NEXT_TURN',
    PREV_PHASE: 'PREV_PHASE',
    NEXT_PHASE: 'NEXT_PHASE',
    PREV_SUBPHASE: 'PREV_SUBPHASE',
    NEXT_SUBPHASE: 'NEXT_SUBPHASE',    
    NEXT_PLAYER: 'NEXT_PLAYER',
    SET_VICTORY: 'SET_VICTORY'
};
